### ISSUE TITLE
Error on last step of tutorial section 5.1

### ISSUE THREAD

**Issue by thodges314** [rustwasm/wasm_game_of_life#44]
I'm working through the tutorial and setting up the boilerplace, etc for the hello world app.  Everything runs smoothly until I get an error on the last step that I cannot diagnose.

`
thodges@lovelace:~/Workspace/Rust/wasm-game-of-life/www$ npm run start

> create-wasm-app@0.1.0 start /home/thodges/Workspace/Rust/wasm-game-of-life/www
> webpack-dev-server

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
Failed to decode custom "name" section @1734; ignoring (integer representation too long).
✖ ｢wdm｣: Hash: cd84f870a9f476e7fb21
Version: webpack 4.29.3
Time: 554ms
Built at: 18/02/2019 12:57:41
         Asset       Size  Chunks             Chunk Names
0.bootstrap.js   3.15 KiB       0  [emitted]  
  bootstrap.js    354 KiB    main  [emitted]  main
    index.html  175 bytes          [emitted]  
Entrypoint main = bootstrap.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./bootstrap.js 40 bytes {main} [built]
[../pkg/wasm_game_of_life.js] 708 bytes {0} [built]
[./bootstrap.js] 279 bytes {main} [built]
[./index.js] 58 bytes {0} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/events/events.js] 13.3 KiB {main} [built]
[./node_modules/html-entities/index.js] 231 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
    + 14 hidden modules

ERROR in ../pkg/wasm_game_of_life_bg.wasm
Module parse failed: Unexpected section: 0xfe
You may need an appropriate loader to handle this file type.
Error: Unexpected section: 0xfe
    at new CompileError (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1542:11)
    at Object.decode (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1559:25)
    at decode (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
    at WebAssemblyParser.parse (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
    at doBuild.err (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/webpack/lib/NormalModule.js:460:32)
    at runLoaders (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/webpack/lib/NormalModule.js:342:12)
    at /home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /home/thodges/Workspace/Rust/wasm-game-of-life/www/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 @ ../pkg/wasm_game_of_life.js 2:0-47 8:71-82 9:45-56 26:11-21
 @ ./index.js
 @ ./bootstrap.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./bootstrap.js

ERROR in chunk 0
ddc111f061f0f6c2679f.module.wasm
/home/thodges/Workspace/Rust/wasm-game-of-life/pkg/wasm_game_of_life_bg.wasm
unexpected end
ℹ ｢wdm｣: Failed to compile.

`

**Comment by fitzgen** [comment]
Thanks for the bug report! This was a bug in the wasm library that webpack uses, and has since been fixed if you update to webpack version to `"^4.29.3"` in `package.json`

https://github.com/webpack/webpack/pull/8786

**Comment by thodges314** [comment]
While that failed (that setting was already in place - and I even tried setting it to 4.29.5, the current version), repeating the process from step 1 but making that change described in rustwasm/book/issues/148 seemed to fix the problem.
