### ISSUE TITLE
"npm init wasm-app www" fails

### ISSUE THREAD

**Issue by Orus78** [rustwasm/wasm_game_of_life#48]
Hello,

I try to follow this tutorial : https://rustwasm.github.io/docs/book/game-of-life/hello-world.html

I get an error when I launch `npm init wasm-app www`

```
PS C:\Orus\Prog\lmt\wasm-game-of-life> npm init wasm-app www
npx: installed 1 in 1.258s
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
PS C:\Orus\Prog\lmt\wasm-game-of-life> node -v
v10.16.0
PS C:\Orus\Prog\lmt\wasm-game-of-life> npm -v
6.9.0
PS C:\Orus\Prog\lmt\wasm-game-of-life>
```

I launched all commands in a PowerShell window.

Could you help me ?

Many thanks,
David.

**Comment by ph-preis** [comment]
In my case, this error simply meant that the path to git.exe was not in the $PATH enviroment variable. However, adding it to there only resulted in another error:
https://github.com/rustwasm/create-wasm-app/issues/44

**Comment by LenRemmerswaal** [comment]
I had the exact same issue working through the same guide.
The problem seems to be the git setup on windows: git is not on the path.
Running `npm init wasm-app www` in a Git Bash console worked for me.

**Comment by DeadBushSanpai** [comment]
I'm running on Linux. After install git and restart console to refresh PATH, this bug fixed.
